Repository leapfrogtechnology/frogtoberfest, pull requests merged in 2019-10, with the labels that each got.

#10 Change link text color to blue
  src/pages/User/components/PullRequests/PullRequest/PullRequestInfo.js
Labels: design, enhancement

#11 Minor cleanup
  package.json
  src/assets/images/frogtoberfest-artwork.png
  src/assets/images/frogtoberfest-logo-1x.png
  src/assets/images/frogtoberfest-logo-2x.png
  src/assets/images/leapfrog-open-source-logo-1x.png
  src/assets/images/leapfrog-open-source-logo-2x.png
  src/components/Footer.js
  src/components/RegisterReminder.js
  src/components/SiteTitle.js
  src/components/UsernameForm/TimeMessage/getTimeMessage.js
  src/pages/User/components/PullRequests/ErrorText.js
  src/pages/User/components/PullRequests/UserInfo/UserImage.js
  src/pages/User/components/PullRequests/index.js
Labels: enhancement

#14 Fix responsive design for footer
  src/components/Footer.js
  src/components/SiteTitle.js
  yarn.lock
Labels: enhancement

#17 Upgrade react, react-scripts and other dev dependencies
  package.json
  yarn.lock
Labels: dependencies

#16 Do not to count pull requests with "invalid" label
  src/pages/User/components/PullRequests/index.js
Labels: bugfix, enhancement, needs improvements

#24 Fix Other Repository count still considering the "invalid" PRs
  src/pages/User/components/PullRequests/index.js
Labels: bugfix

#19 Show challenge completed text after challenge completion
  src/components/SiteDetails.js
  src/components/UsernameForm/CompletionMessage.js
  src/components/UsernameForm/index.js
  src/config.js
  src/pages/User/components/PullRequests/PullRequest/index.js
  src/pages/User/components/PullRequests/ShareButtons.js
  src/pages/User/components/PullRequests/UserInfo/MotivationalMessage/getMessage.js
  src/pages/User/components/PullRequests/UserInfo/MotivationalMessage/index.js
  src/pages/User/components/PullRequests/UserInfo/ResultMessage/getResultMessage.js
  src/pages/User/components/PullRequests/UserInfo/UserImage.js
  src/pages/User/components/PullRequests/UserInfo/index.js
  src/pages/User/components/PullRequests/index.js
  src/pages/User/components/PullRequests/pullRequestAmount.js
  src/pages/User/index.js
Labels: enhancement, feature

#25 Update design of Frogtoberfest home page
  src/App.js
  src/components/Footer.js
  src/components/GithubCorner/GithubCorner.css
  src/components/GithubCorner/index.js
  src/components/PageWrapper.js
  src/components/SiteDetails.js
  src/components/SiteTitle.js
  src/components/UsernameForm/CheckButton.js
  src/components/UsernameForm/UsernameInput.js
  src/components/UsernameForm/index.js
  src/index.css
Labels: design, enhancement, ux

#26 Improve input text styles
  src/components/SiteTitle.js
  src/components/UsernameForm/CheckButton.js
  src/components/UsernameForm/UsernameInput.js
  src/components/UsernameForm/index.js
Labels: enhancement

#28 Fix design inconsistency
  src/components/SiteDetails.js
  src/components/SiteTitle.js
  src/components/UsernameForm/TimeMessage/index.js
  src/components/UsernameForm/UsernameInput.js
  src/components/UsernameForm/index.js
  src/index.css
Labels: design, enhancement, ux

#30 Open PR links in new tab
  src/pages/User/components/PullRequests/PullRequest/PullRequestInfo.js
Labels: enhancement

#32 Setup test environment and add tests for formatDate
  .travis.yml
  src/utils/utils.spec.js
Labels: ci, test

#34 Better info for users who are not in Leapfrog GitHub Organization
  src/config.js
  src/pages/User/components/PullRequests/index.js
  src/pages/User/index.js
Labels: design, enhancement, ux

#36 Better date format on the pull request history
  src/utils/utils.js
  src/utils/utils.spec.js
Labels: design, ux

#39 Frogtoberfest Completion Message Not Showing and Other Repo Invalid Count Still Being Counted
  src/pages/User/components/PullRequests/index.js
  src/pages/User/index.js
Labels: bugfix

#41 Enhance user experience on clicking 'this is me' button
  src/pages/User/components/PullRequests/MeLinkInfo.js
Labels: ux
